### ISSUE TITLE
連番画像を出力すると「ファイルの出力に失敗しました。」メッセージが出る

### ISSUE THREAD

**Issue by ePi5131** [rigaya/ffmpegOut#2]
### やったこと
・適当な編集プロジェクトを用意する
・プロファイルをプリセットの「png連番」にする
・他の設定は弄らずに適当な名前を付けて保存を押下

### 起きたこと
AviUtl「ファイルの出力に失敗しました。」というメッセージボックスが表示される
コンソールには「auo [warning]: 出力ファイルが見つかりませんでした。」との表示がされる
出力されたファイルを見ると、出力自体は正常にできている模様

### 期待される動作
メッセージボックスが表示されない

### 環境
Windows 11/AviUtl version 1.10/拡張編集 version 0.92/ffmpegOut 0.10

**Comment by rigaya** [comment]
問題点をお知らせいただきありがとうございます。

たしかに出力ファイルの存在チェックに引っかかってエラー扱いになってしまっておりました。

遅くなりましたが、[ffmpegOut 0.11](https://github.com/rigaya/ffmpegOut/releases/tag/0.11)で修正しました。

**Comment by rigaya** [comment]
修正できているかと思いますので、closeいたします。問題あれば、お手数ですが再度openください。

ご指摘ありがとうございました。
