### ISSUE TITLE
ffmpegに渡す転送色空間について

### ISSUE THREAD

**Issue by kiyoken1594** [rigaya/ffmpegOut#3]
質問失礼いたします。
yuv 420, 422, 444, 420(16bit), 444(16bit), rgb, rgba以外でffmpegに動画情報を渡すことはできますか？
例えば、YUVA444(16 bit)や、RGBA(16 bit)などです。

**Comment by rigaya** [comment]
結論から申しますと、YUVA444(16bit)や、RGBA(16bit)では、渡すことはできません。

Aviutlで透過情報(アルファ値)を扱うのは拡張編集使用時ですが、このときのAviutlの内部色空間は rgba(8bit)となっています。そのため、16bitを用いてffmpegに転送する必要はないと考えています。

拡張編集使用時以外のフィルタでは、内部色空間がYC48(12bit精度)のため、これを転送するためYUV444(16bit)などが用意されています。ただし、この場合は透過情報を含みません。

**Comment by kiyoken1594** [comment]
回答有り難うございます。
YUVA 16bitやRGBA 16bitはAviutlではできないのですね。
了解いたしました。迅速な回答感謝します。
