### ISSUE TITLE
ffmpegOut 1.09にて一面が緑の映像しか出ません

### ISSUE THREAD

**Issue by resistorsytrus** [rigaya/ffmpegOut#4]
以下ログです
------------------------------------------------------------------------------------------------------------------------------
[C:\Users\yyuuk\Opia - 1080p24.mkv]
------------------------------------------------------------------------------------------------------------------------------
auo [info]: ffmpegOut 1.09 / Windows 11 x64 (22631) / Intel Pentium(R) Silver J5005 @ 1.50GHz [TB: 2.69GHz] (4C/4T)
auo [info]: video: 0:03:15.041 24/1(24.000) fps
auo [info]: audio: 0:03:11.231 2ch 44.1kHz 8433288 samples
auo [info]:  ffmpegとして "..\ffmpeg-master-latest-win64-gpl-shared\bin\ffmpeg.exe" を使用します。
auo [info]: converting YC48 -> nv12p(16bit), using SSE2 SSSE3 SSE4.1
auo [info]: ffmpeg options...
 -y -f rawvideo -s 1920x1080 -pix_fmt p010le -r 24/1 -i "-" -i "\\.\pipe\Aviutl00002138_AuoAudioPipe0" -c:v libsvtav1 -crf 35
-preset 13 -tile_columns 1 -tile_rows 1 -svtav1-params "enable-overlays=1:tune=0:enable-qm=1:qm-min=0:keyint=0" -c:a libopus
-b:a 128k -frame_duration 120 -map_metadata -1 "C:\Users\yyuuk\Opia - 1080p24.0.mkv"
ffmpeg version n6.1.1-20231231 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config
--cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug
--disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi
--enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse
--enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth
--enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm
--enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray
--enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx
--enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel
--enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm
--enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265
--enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags=
--extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20231231
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, rawvideo, from 'fd:':
  Duration: N/A, start: 0.000000, bitrate: 1194393 kb/s
  Stream #0:0: Video: rawvideo, p010le, 1920x1080, 1194393 kb/s, 24 tbr, 24 tbn
auo [info]: CUSTOM で音声エンコードを行います。 custom
[aist#1:0/pcm_s16le @ 0000019e6ca27b80] Guessed Channel Layout: stereo
Input #1, wav, from '\\.\pipe\Aviutl00002138_AuoAudioPipe0':
  Duration: N/A, bitrate: 1411 kb/s
  Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> av1 (libsvtav1))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> opus (libopus))
[libsvtav1 @ 0000019e6ca1cf00] The "tile_columns" option is deprecated: Log2 of number of tile columns to use (Deprecated,
use svtav1-params)
[libsvtav1 @ 0000019e6ca1cf00] The "tile_rows" option is deprecated: Log2 of number of tile rows to use (Deprecated, use svtav1-params)
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.8.0
Svt[info]: SVT [build]  :	GCC 13.2.0	 64 bit
Svt[info]: LIB Build date: Dec 26 2023 00:16:14
Svt[info]: -------------------------------------------
Svt[warn]: EncoderMode (preset): 13 was developed for the sole purpose of debugging and or running fast convex-hull encoding.
           This configuration should not be used for any benchmarking or quality analysis
Svt[warn]: If you are using tiles with the intent of increasing the decoder speed, please also consider using --fast-decode
           1, especially if the intended decoder is running with limited multi-threading capabilities.
Svt[info]: Number of logical cores available: 4
Svt[info]: Number of PPCS 84
Svt[info]: [asm level on system : up to sse4_2]
Svt[info]: [asm level selected : up to sse4_2]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: main profile	tier (auto)	level (auto)
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator 		: 1920 / 1080 / 24 / 1
Svt[info]: SVT [config]: bit-depth / color format 					: 10 / YUV420
Svt[info]: SVT [config]: preset / tune / pred struct 					: 13 / VQ / random access
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type 			: 0 / 16 / key frame
Svt[info]: SVT [config]: BRC mode / rate factor 					: CRF / 35 
Svt[info]: -------------------------------------------
[in#1/wav @ 0000019e6ca178c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Output #0, matroska, to 'C:\Users\yyuuk\Opia - 1080p24.0.mkv':
  Metadata:
    encoder         : Lavf60.16.100
  Stream #0:0: Video: av1 (AV01 / 0x31305641), yuv420p10le(tv, progressive), 1920x1080, q=2-31, 24 fps, 1k tbn
    Metadata:
      encoder         : Lavc60.31.102 libsvtav1
  Stream #0:1: Audio: opus ([255][255][255][255] / 0xFFFFFFFF), 48000 Hz, stereo, s16, 128 kb/s
    Metadata:
      encoder         : Lavc60.31.102 libopus
[in#0/rawvideo @ 0000019e6c9babc0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
frame= 3105 fps= 11 q=25.0 size=    2048kB time=00:02:11.51 bitrate= 127.6kbits/s speed=0.448x    
auo [info]: 音声処理の終了を待機しています...
[out#0/matroska @ 0000019e6c9eacc0] video:330kB audio:2980kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.959363%
frame= 4681 fps= 11 q=26.0 Lsize=    3342kB time=00:03:15.00 bitrate= 140.4kbits/s speed=0.456x    
auo [info]: CPU使用率: Aviutl: 23.73% / ffmpeg: 25.14%
auo [info]: ffmpegエンコード時間 : 0時間 7分 7.8秒
auo [info]: 音声処理の終了を待機しています...
auo [info]: 総エンコード時間   : 0時間 7分 8.5秒

**Comment by rigaya** [comment]
ご報告ありがとうございます。[ffmpegOut 1.10](https://github.com/rigaya/ffmpegOut/releases/tag/1.10)で修正できているかと思います。
