### ISSUE TITLE
How to get full control of the ffmpeg command

### ISSUE THREAD

**Issue by iJzFan** [rigaya/ffmpegOut#5]
I want to encode with -pix_fmt yuva420p10le.

**Comment by iJzFan** [comment]
Actually, what I want to do is convert it to animated avif with alpha and 10bit.
https://sliberte.net/archives/1162

**Comment by rigaya** [comment]
ffmpegOut only supports rgba format when handling alpha channel, as the native format of exedit is rgba.

I think you can then convert rgba to another format inside ffmpeg if required.

However, conversion using pipe to avifenc is not possible in ffmpegOut, you should better think writing in another format and then converting to avif.
